"""Registry of all static rules (ALL_RULES list) used by V1 and V2."""
from __future__ import annotations
from aws_arch_agent.rules.security import (
    IamWildcardAction, IamWildcardResource, OpenSshToWorld, OpenDbPortsToWorld,
    S3PublicAccessNotBlocked, S3EncryptionMissing, KmsKeyPolicyWildcard, DynamoDbEncryptionMissing,
    ApiGatewayAuthMissing, ApiGatewayTlsVersion, AlbHttpsRedirect, AlbSslPolicy,
    SqsEncryptionMissing, SnsEncryptionMissing, SecretsManagerRotation, HardcodedSecrets,
    LambdaEnvSecrets, CloudFrontHttpsOnly, CloudFrontLegacyTls, EcsReadonlyRootFs,
    RdsSslConnection, VpcEndpointsMissing, KmsKeyRotation, WafMissing,
    ElastiCacheEncryption, SecurityHubNotEnabled, GuardDutyNotEnabled,
    # New security rules
    EcrImageScanning, EcrImageImmutability, EcrLifecyclePolicy, Route53HealthChecks, Route53Dnssec,
    SsmParameterEncryption, CognitoMfaMissing, CognitoPasswordPolicy, CognitoAdvancedSecurity,
    EfsEncryptionMissing, KinesisEncryption, OpenSearchEncryption, OpenSearchFineGrainedAccess,
    OpenSearchVpcOnly, AthenaEncryption, GlueEncryption, MskEncryption, MskAuthentication,
    SagemakerNotebookVpc, SagemakerEncryption, AppSyncLogging, AppSyncWaf, FsxEncryption,
    TransferFamilyLogging, CodePipelineEncryption, CodeBuildPrivilegedMode, SecurityGroupEgressOpen,
    NaclMissing, StackTerminationProtection,
)
from aws_arch_agent.rules.reliability import (
    RdsMultiAzMissing, BackupRetentionMissing, LambdaDlqMissing,
    DynamoDbPitrMissing, DynamoDbBackupMissing, ApiGatewayThrottling, AlbHealthCheck,
    SqsDlqMissing, LambdaTimeout, LambdaVpcAccess, RdsReadReplicas, NatGatewaySingleAz,
    BackupVaultMissing, CrossRegionBackup, StepFunctionsRetry, ElastiCacheMultiAz,
    # New reliability rules
    EfsBackupPolicy, EfsLifecyclePolicy, KinesisRetention, GlobalAcceleratorHealthChecks,
    CodePipelineApproval, AcmCertificateValidation,
)
from aws_arch_agent.rules.cost import (
    LogRetentionNeverExpire, MissingAutoscalingHint, DynamoDbAutoscalingMissing,
    LambdaProvisionedConcurrency, RdsReservedInstances, NatGatewayCosts,
    # New cost rules
    S3IntelligentTiering, EbsGp2ToGp3, ElastiCacheReservedNodes, RdsGraviton,
    CloudFrontPriceClass, UnusedEips, S3LifecycleMissing,
)
from aws_arch_agent.rules.best_practices import MissingStandardTags, SecretsInEnvVars
from aws_arch_agent.rules.operational_excellence import (
    CloudTrailMissing, VpcFlowLogsMissing, XRayTracingMissing, DynamoDbStreamsMissing,
    ApiGatewayAccessLogs, AlbAccessLogs, CloudFrontAccessLogs, EcsContainerInsights,
    RdsEnhancedMonitoring, CloudWatchAlarmsMissing, SnsAlarmNotifications,
    StepFunctionsXRay, EventBridgeDlq, ConfigNotEnabled,
    # New operational excellence rules
    GlueJobMetrics, TransitGatewayFlowLogs, CodePipelineNotifications, AppRunnerObservability,
    GlueJobBookmarks, CodeBuildLogging,
)
from aws_arch_agent.rules.performance_efficiency import (
    GravitonNotUsed, CachingHint, DynamoDbProvisionedCapacity,
    ApiGatewayCaching, LambdaMemoryOptimization, CloudFrontCaching,
    EcsTaskSizing, RdsInstanceSizing,
    # New performance efficiency rules
    KinesisEnhancedFanout, OpenSearchInstanceTypes, GlobalAcceleratorOptimization,
    EfsPerformanceMode, AppSyncCaching, S3TransferAcceleration,
)
from aws_arch_agent.rules.sustainability import SpotNotConsidered, RightSizingHint

ALL_RULES = [
    # Security (56 rules)
    IamWildcardAction(),
    IamWildcardResource(),
    OpenSshToWorld(),
    OpenDbPortsToWorld(),
    S3PublicAccessNotBlocked(),
    S3EncryptionMissing(),
    KmsKeyPolicyWildcard(),
    DynamoDbEncryptionMissing(),
    ApiGatewayAuthMissing(),
    ApiGatewayTlsVersion(),
    AlbHttpsRedirect(),
    AlbSslPolicy(),
    SqsEncryptionMissing(),
    SnsEncryptionMissing(),
    SecretsManagerRotation(),
    HardcodedSecrets(),
    LambdaEnvSecrets(),
    CloudFrontHttpsOnly(),
    CloudFrontLegacyTls(),
    EcsReadonlyRootFs(),
    RdsSslConnection(),
    VpcEndpointsMissing(),
    KmsKeyRotation(),
    WafMissing(),
    ElastiCacheEncryption(),
    SecurityHubNotEnabled(),
    GuardDutyNotEnabled(),
    EcrImageScanning(),
    EcrImageImmutability(),
    EcrLifecyclePolicy(),
    Route53HealthChecks(),
    Route53Dnssec(),
    SsmParameterEncryption(),
    CognitoMfaMissing(),
    CognitoPasswordPolicy(),
    CognitoAdvancedSecurity(),
    EfsEncryptionMissing(),
    KinesisEncryption(),
    OpenSearchEncryption(),
    OpenSearchFineGrainedAccess(),
    OpenSearchVpcOnly(),
    AthenaEncryption(),
    GlueEncryption(),
    MskEncryption(),
    MskAuthentication(),
    SagemakerNotebookVpc(),
    SagemakerEncryption(),
    AppSyncLogging(),
    AppSyncWaf(),
    FsxEncryption(),
    TransferFamilyLogging(),
    CodePipelineEncryption(),
    CodeBuildPrivilegedMode(),
    SecurityGroupEgressOpen(),
    NaclMissing(),
    StackTerminationProtection(),
    # Reliability (22 rules)
    RdsMultiAzMissing(),
    BackupRetentionMissing(),
    LambdaDlqMissing(),
    DynamoDbPitrMissing(),
    DynamoDbBackupMissing(),
    ApiGatewayThrottling(),
    AlbHealthCheck(),
    SqsDlqMissing(),
    LambdaTimeout(),
    LambdaVpcAccess(),
    RdsReadReplicas(),
    NatGatewaySingleAz(),
    BackupVaultMissing(),
    CrossRegionBackup(),
    StepFunctionsRetry(),
    ElastiCacheMultiAz(),
    EfsBackupPolicy(),
    EfsLifecyclePolicy(),
    KinesisRetention(),
    GlobalAcceleratorHealthChecks(),
    CodePipelineApproval(),
    AcmCertificateValidation(),
    # Cost Optimization (13 rules)
    LogRetentionNeverExpire(),
    MissingAutoscalingHint(),
    DynamoDbAutoscalingMissing(),
    LambdaProvisionedConcurrency(),
    RdsReservedInstances(),
    NatGatewayCosts(),
    S3IntelligentTiering(),
    EbsGp2ToGp3(),
    ElastiCacheReservedNodes(),
    RdsGraviton(),
    CloudFrontPriceClass(),
    UnusedEips(),
    S3LifecycleMissing(),
    # Best Practices (2 rules)
    MissingStandardTags(),
    SecretsInEnvVars(),
    # Operational Excellence (20 rules)
    CloudTrailMissing(),
    VpcFlowLogsMissing(),
    XRayTracingMissing(),
    DynamoDbStreamsMissing(),
    ApiGatewayAccessLogs(),
    AlbAccessLogs(),
    CloudFrontAccessLogs(),
    EcsContainerInsights(),
    RdsEnhancedMonitoring(),
    CloudWatchAlarmsMissing(),
    SnsAlarmNotifications(),
    StepFunctionsXRay(),
    EventBridgeDlq(),
    ConfigNotEnabled(),
    GlueJobMetrics(),
    TransitGatewayFlowLogs(),
    CodePipelineNotifications(),
    AppRunnerObservability(),
    GlueJobBookmarks(),
    CodeBuildLogging(),
    # Performance Efficiency (14 rules)
    GravitonNotUsed(),
    CachingHint(),
    DynamoDbProvisionedCapacity(),
    ApiGatewayCaching(),
    LambdaMemoryOptimization(),
    CloudFrontCaching(),
    EcsTaskSizing(),
    RdsInstanceSizing(),
    KinesisEnhancedFanout(),
    OpenSearchInstanceTypes(),
    GlobalAcceleratorOptimization(),
    EfsPerformanceMode(),
    AppSyncCaching(),
    S3TransferAcceleration(),
    # Sustainability (2 rules)
    SpotNotConsidered(),
    RightSizingHint(),
]
