"""Registry of all static rules (ALL_RULES list) used by V1 and V2."""
from __future__ import annotations
from aws_arch_agent.rules.security import (
    IamWildcardAction, IamWildcardResource, OpenSshToWorld, OpenDbPortsToWorld,
    S3PublicAccessNotBlocked, S3EncryptionMissing, KmsKeyPolicyWildcard, DynamoDbEncryptionMissing,
    ApiGatewayAuthMissing, ApiGatewayTlsVersion, AlbHttpsRedirect, AlbSslPolicy,
    SqsEncryptionMissing, SnsEncryptionMissing, SecretsManagerRotation, HardcodedSecrets,
    LambdaEnvSecrets, CloudFrontHttpsOnly, CloudFrontLegacyTls, EcsReadonlyRootFs,
    RdsSslConnection, VpcEndpointsMissing, KmsKeyRotation, WafMissing,
    ElastiCacheEncryption, SecurityHubNotEnabled, GuardDutyNotEnabled,
    EcrImageScanning, EcrImageImmutability, EcrLifecyclePolicy, Route53HealthChecks, Route53Dnssec,
    SsmParameterEncryption, CognitoMfaMissing, CognitoPasswordPolicy, CognitoAdvancedSecurity,
    EfsEncryptionMissing, KinesisEncryption, OpenSearchEncryption, OpenSearchFineGrainedAccess,
    OpenSearchVpcOnly, AthenaEncryption, GlueEncryption, MskEncryption, MskAuthentication,
    SagemakerNotebookVpc, SagemakerEncryption, AppSyncLogging, AppSyncWaf, FsxEncryption,
    TransferFamilyLogging, CodePipelineEncryption, CodeBuildPrivilegedMode, SecurityGroupEgressOpen,
    NaclMissing, StackTerminationProtection,
    LambdaFunctionUrlAuth, EcsTaskRunAsRoot, RedshiftEncryptionMissing, DocumentDbEncryptionMissing,
    NeptuneEncryptionMissing, CloudWatchLogsKmsEncryption, BackupVaultEncryption,
    RdsPubliclyAccessible, MacieNotEnabled,
)
from aws_arch_agent.rules.reliability import (
    RdsMultiAzMissing, BackupRetentionMissing, LambdaDlqMissing,
    DynamoDbPitrMissing, DynamoDbBackupMissing, ApiGatewayThrottling, AlbHealthCheck,
    SqsDlqMissing, LambdaTimeout, LambdaVpcAccess, RdsReadReplicas, NatGatewaySingleAz,
    BackupVaultMissing, CrossRegionBackup, StepFunctionsRetry, ElastiCacheMultiAz,
    EfsBackupPolicy, EfsLifecyclePolicy, KinesisRetention, GlobalAcceleratorHealthChecks,
    CodePipelineApproval, AcmCertificateValidation,
    BlueGreenDeploymentMissing, SqsVisibilityTimeout, DynamoDbGlobalTables, S3ReplicationMissing,
    LambdaReservedConcurrency, ApiGatewayRequestValidator, EventBridgeRetryPolicy,
    RdsDeletionProtection, S3VersioningMissing,
)
from aws_arch_agent.rules.cost import (
    LogRetentionNeverExpire, MissingAutoscalingHint, DynamoDbAutoscalingMissing,
    LambdaProvisionedConcurrency, RdsReservedInstances, NatGatewayCosts,
    S3IntelligentTiering, EbsGp2ToGp3, ElastiCacheReservedNodes, RdsGraviton,
    CloudFrontPriceClass, UnusedEips, S3LifecycleMissing,
    AwsBudgetsMissing, CostAllocationTags, SavingsPlansOpportunity,
    LambdaPowerTuning, S3StorageLens,
)
from aws_arch_agent.rules.best_practices import (
    MissingStandardTags, SecretsInEnvVars,
    ResourceNamingConvention, CdkAspectsMissing, CdkContextMissing,
)
from aws_arch_agent.rules.operational_excellence import (
    CloudTrailMissing, VpcFlowLogsMissing, XRayTracingMissing, DynamoDbStreamsMissing,
    ApiGatewayAccessLogs, AlbAccessLogs, CloudFrontAccessLogs, EcsContainerInsights,
    RdsEnhancedMonitoring, CloudWatchAlarmsMissing, SnsAlarmNotifications,
    StepFunctionsXRay, EventBridgeDlq, ConfigNotEnabled,
    GlueJobMetrics, TransitGatewayFlowLogs, CodePipelineNotifications, AppRunnerObservability,
    GlueJobBookmarks, CodeBuildLogging,
    CloudWatchDashboardMissing, ResourceTaggingStrategy, SsmParameterAdvancedTier,
    LambdaReservedConcurrencyHint, S3ReplicationMetrics,
)
from aws_arch_agent.rules.performance_efficiency import (
    GravitonNotUsed, CachingHint, DynamoDbProvisionedCapacity,
    ApiGatewayCaching, LambdaMemoryOptimization, CloudFrontCaching,
    EcsTaskSizing, RdsInstanceSizing,
    KinesisEnhancedFanout, OpenSearchInstanceTypes, GlobalAcceleratorOptimization,
    EfsPerformanceMode, AppSyncCaching, S3TransferAcceleration,
    LambdaSnapStart, AuroraIoOptimized, EbsIo2BlockExpress,
    CloudWatchContributorInsights, RdsProxyMissing,
)
from aws_arch_agent.rules.sustainability import (
    SpotNotConsidered, RightSizingHint,
    ScheduledScalingMissing, AsyncProcessingHint, ManagedServicesPreference,
    CloudFrontCompression, LatestGenInstances,
)

ALL_RULES = [
    # Security (65 rules)
    IamWildcardAction(),
    IamWildcardResource(),
    OpenSshToWorld(),
    OpenDbPortsToWorld(),
    S3PublicAccessNotBlocked(),
    S3EncryptionMissing(),
    KmsKeyPolicyWildcard(),
    DynamoDbEncryptionMissing(),
    ApiGatewayAuthMissing(),
    ApiGatewayTlsVersion(),
    AlbHttpsRedirect(),
    AlbSslPolicy(),
    SqsEncryptionMissing(),
    SnsEncryptionMissing(),
    SecretsManagerRotation(),
    HardcodedSecrets(),
    LambdaEnvSecrets(),
    CloudFrontHttpsOnly(),
    CloudFrontLegacyTls(),
    EcsReadonlyRootFs(),
    RdsSslConnection(),
    VpcEndpointsMissing(),
    KmsKeyRotation(),
    WafMissing(),
    ElastiCacheEncryption(),
    SecurityHubNotEnabled(),
    GuardDutyNotEnabled(),
    EcrImageScanning(),
    EcrImageImmutability(),
    EcrLifecyclePolicy(),
    Route53HealthChecks(),
    Route53Dnssec(),
    SsmParameterEncryption(),
    CognitoMfaMissing(),
    CognitoPasswordPolicy(),
    CognitoAdvancedSecurity(),
    EfsEncryptionMissing(),
    KinesisEncryption(),
    OpenSearchEncryption(),
    OpenSearchFineGrainedAccess(),
    OpenSearchVpcOnly(),
    AthenaEncryption(),
    GlueEncryption(),
    MskEncryption(),
    MskAuthentication(),
    SagemakerNotebookVpc(),
    SagemakerEncryption(),
    AppSyncLogging(),
    AppSyncWaf(),
    FsxEncryption(),
    TransferFamilyLogging(),
    CodePipelineEncryption(),
    CodeBuildPrivilegedMode(),
    SecurityGroupEgressOpen(),
    NaclMissing(),
    StackTerminationProtection(),
    LambdaFunctionUrlAuth(),
    EcsTaskRunAsRoot(),
    RedshiftEncryptionMissing(),
    DocumentDbEncryptionMissing(),
    NeptuneEncryptionMissing(),
    CloudWatchLogsKmsEncryption(),
    BackupVaultEncryption(),
    RdsPubliclyAccessible(),
    MacieNotEnabled(),
    # Reliability (31 rules)
    RdsMultiAzMissing(),
    BackupRetentionMissing(),
    LambdaDlqMissing(),
    DynamoDbPitrMissing(),
    DynamoDbBackupMissing(),
    ApiGatewayThrottling(),
    AlbHealthCheck(),
    SqsDlqMissing(),
    LambdaTimeout(),
    LambdaVpcAccess(),
    RdsReadReplicas(),
    NatGatewaySingleAz(),
    BackupVaultMissing(),
    CrossRegionBackup(),
    StepFunctionsRetry(),
    ElastiCacheMultiAz(),
    EfsBackupPolicy(),
    EfsLifecyclePolicy(),
    KinesisRetention(),
    GlobalAcceleratorHealthChecks(),
    CodePipelineApproval(),
    AcmCertificateValidation(),
    BlueGreenDeploymentMissing(),
    SqsVisibilityTimeout(),
    DynamoDbGlobalTables(),
    S3ReplicationMissing(),
    LambdaReservedConcurrency(),
    ApiGatewayRequestValidator(),
    EventBridgeRetryPolicy(),
    RdsDeletionProtection(),
    S3VersioningMissing(),
    LogRetentionNeverExpire(),
    MissingAutoscalingHint(),
    DynamoDbAutoscalingMissing(),
    LambdaProvisionedConcurrency(),
    RdsReservedInstances(),
    NatGatewayCosts(),
    S3IntelligentTiering(),
    EbsGp2ToGp3(),
    ElastiCacheReservedNodes(),
    RdsGraviton(),
    CloudFrontPriceClass(),
    UnusedEips(),
    S3LifecycleMissing(),
    AwsBudgetsMissing(),
    CostAllocationTags(),
    SavingsPlansOpportunity(),
    LambdaPowerTuning(),
    S3StorageLens(),
    # Best Practices (5 rules)
    MissingStandardTags(),
    SecretsInEnvVars(),
    ResourceNamingConvention(),
    CdkAspectsMissing(),
    CdkContextMissing(),
    # Operational Excellence (20 rules)
    CloudTrailMissing(),
    VpcFlowLogsMissing(),
    XRayTracingMissing(),
    DynamoDbStreamsMissing(),
    ApiGatewayAccessLogs(),
    AlbAccessLogs(),
    CloudFrontAccessLogs(),
    EcsContainerInsights(),
    RdsEnhancedMonitoring(),
    CloudWatchAlarmsMissing(),
    SnsAlarmNotifications(),
    StepFunctionsXRay(),
    EventBridgeDlq(),
    ConfigNotEnabled(),
    GlueJobMetrics(),
    TransitGatewayFlowLogs(),
    CodePipelineNotifications(),
    AppRunnerObservability(),
    GlueJobBookmarks(),
    CodeBuildLogging(),
    CloudWatchDashboardMissing(),
    ResourceTaggingStrategy(),
    SsmParameterAdvancedTier(),
    LambdaReservedConcurrencyHint(),
    S3ReplicationMetrics(),
    # Performance Efficiency (19 rules)
    GravitonNotUsed(),
    CachingHint(),
    DynamoDbProvisionedCapacity(),
    ApiGatewayCaching(),
    LambdaMemoryOptimization(),
    CloudFrontCaching(),
    EcsTaskSizing(),
    RdsInstanceSizing(),
    KinesisEnhancedFanout(),
    OpenSearchInstanceTypes(),
    GlobalAcceleratorOptimization(),
    EfsPerformanceMode(),
    AppSyncCaching(),
    S3TransferAcceleration(),
    LambdaSnapStart(),
    AuroraIoOptimized(),
    EbsIo2BlockExpress(),
    CloudWatchContributorInsights(),
    RdsProxyMissing(),
    # Sustainability (7 rules)
    SpotNotConsidered(),
    RightSizingHint(),
    ScheduledScalingMissing(),
    AsyncProcessingHint(),
    ManagedServicesPreference(),
    CloudFrontCompression(),
    LatestGenInstances(),
]
